image: eclipse-temurin:17-jdk

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "11076708"

before_script:
  - apt-get update -qq && apt-get install -y wget tar unzip lib32stdc++6 lib32z1
  - export ANDROID_SDK_ROOT="${PWD}/android-home"
  - mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
  - wget -q -O $ANDROID_SDK_ROOT/cmdline-tools.zip "https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip"
  - unzip -d $ANDROID_SDK_ROOT/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools.zip
  - mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/tools || true
  - export PATH=$PATH:${ANDROID_SDK_ROOT}/cmdline-tools/tools/bin/
  - sdkmanager --verbose --version
  - yes | sdkmanager --licenses || true
  - sdkmanager --verbose "platforms;android-${ANDROID_COMPILE_SDK}" "platform-tools" "build-tools;${ANDROID_BUILD_TOOLS}" || true
  - apt-get update && apt-get install -y curl unzip
  - curl -sL https://firebase.tools | bash
  - chmod +x ./gradlew


stages:
  - build
  - test
  - quality_assurance
  - deploy
  - fabric
  - prod

build:
  stage: build
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/

unitTests:
  stage: test
  script:
    - ./gradlew test

static_analysis:
  stage: quality_assurance
  script:
    - ./gradlew lint
    - ./gradlew detekt
  artifacts:
    paths:
    - app/build/reports/


firebase_deploy:
  stage: deploy
  script:
    - |
      chmod +x ./gradlew
      firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk \
      --app 1:715489346527:android:b1523bff01e22fe47d3a6a \
      --groups "testers" \
      --token "$FIREBASE_TOKEN"